;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        c-electric-semi&comma
        cua--prefix-override-handler
        cua-cut-region
        cua-delete-region
        cua-paste
        enh-ruby-electric-brace
        go-mode-insert-and-indent
        haml-electric-backspace
        indent-for-tab-command
        ledger-magic-tab
        ledger-post-align-xact
        markdown-exdent-or-delete
        org-self-insert-command
        ruby-end-space
        sgml-slash
        sh-assignment
        smart-line-beginning
        smart-move-line-beginning
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        describe-key
        end-of-buffer
        ido-find-file
        ido-switch-buffer
        mouse-set-region
        smex
        ))
