;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua--prefix-override-handler
        cua-cut-region
        cua-delete-region
        cua-paste
        enh-ruby-electric-brace
        go-mode-insert-and-indent
        org-self-insert-command
        ruby-end-space
        smart-line-beginning
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        end-of-buffer
        ido-switch-buffer
        mouse-set-region
        ))
